### PR TITLE
Add user setting to hide contextual menu item

### PR DESCRIPTION
**Pull request by Gofake1**
Added a checkbox in the settings page to toggle on/off the "Find style for this website" menu item.

### CODE REVIEW

**Comment by 350d** [comment]
Hi! Can you provide any use case for this option? Thank you.

**Comment by Gofake1** [comment]
Opened #20

**Comment by 350d** [comment]
Make sense.

**Comment by 350d** [comment]
Option to disable context menu item now available on Settings page in new version 1.9.3

**Pull request closed without merging**
